services:
    pms:
        image: plexinc/pms-docker:latest
        container_name: pms
        restart: unless-stopped
        network_mode: host 
        volumes:
            - ./pms:/config
            - ./pms:/transcode
            - YOUR_MEDIA_DIR:/data
    tuner:
        image: nandyalu/python-ffmpeg
        container_name: tuner
        restart: unless-stopped
        network_mode: host
        volumes:
            - ./:/app
        working_dir: /app
        command: python -m tuner tuner.cfg
        environment:
            SERVER_IP: YOUR_IP_HERE
