services:
    tuner:
        build: .
        container_name: tuner
        restart: unless-stopped
        network_mode: host
        volumes:
            - ./tuner.cfg:/app/tuner.cfg
        working_dir: /app
        command: python -m tuner tuner.cfg
        environment:
          SERVER_IP: YOUR_IP_HERE
          CMD: ffmpeg -hide_banner -loglevel error -user_agent tuner -i %s -c copy -c:a ac3 -copyts -f mpegts pipe:1
